---
title: "Data_Lamberts_Gannet"
author: "Lerusha Naidoo"
date: "2025-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE}
library(BIRDIE)
library(CWAC)
library(ABAP)
library(dplyr)
library(ggplot2)
library(stringr)
library(sf)
library(futile.logger)
library(NicheMapR)
```

*I've change the species (line 30, 31) *
```{r}
# Get list of all CWAC species
spp_list <- listCwacSpp()

# Get ID data for Egyptian goose
genus <- "Morus"
sp_epithet <- "capensis"
sp_ID_dat <- spp_list %>%
  filter(Genus == genus & Species == sp_epithet) %>%
  slice(1)
sp_ID_dat
# Get species code
sp_code = sp_ID_dat$SppRef

# Get list of all CWAC sites in the Western Cape
sites <- listCwacSites(.region_type = "province", .region = "Western Cape")

# Select data for the Eerste River Estuary only
LambertsB <- sites %>% filter(LocationName == "Lamberts Bay: Bird Island")
LambertsB

# Download all counts for this site
bird_counts <- getCwacSiteCounts(LambertsB$LocationCode)

# Select data for species of interest only
sp_counts <- bird_counts %>% filter(Genus == genus & Species == sp_epithet)
sp_counts = sp_counts[-1,]

# Visualise counts for species of interest
sp_counts %>%
  ggplot(aes(x = StartDate, y = Count)) +
  geom_line() +
  geom_point() +
  # labs(title = "Hourly Data",
  #      x = "Date",
  #      y = "Value") +
  theme_minimal()

# Get pentad for Eerste River Estuary (this is just an easy way to get a "polygon" for our study site so that we can get environmental covariate data later)
pentads_wc <- getRegionPentads(.region_type = "province", .region = "Western Cape") #Get all WC pentads
pentad_id <-findPentadFromCoords(as.numeric(LambertsB$Y), as.numeric(LambertsB$X)) #Get ID for Eerste River Estuary
pentad_site <- pentads_wc %>% filter(pentad == pentad_id)
```

*I couldn't think here so I didn't write a loop which would have been easier. I manually changed var = (line 75) and then lines 95-99 were added in after each new run. If anyone wants to make it a loop, much appreciated.* 
```{r}
# enter in longitude, latitude here
x<-c(18.30181, -32.08926)

# enter in variable you want to download see: http://thredds.northwestknowledge.net:8080/thredds/terraclimate_aggregated.html
var="ppt"

#install.packages("ncdf4")
library(ncdf4)

baseurlagg <- paste0(paste0("http://thredds.northwestknowledge.net:8080/thredds/dodsC/agg_terraclimate_",var),"_1958_CurrentYear_GLOBE.nc")

nc <- nc_open(baseurlagg)
lon <- ncvar_get(nc, "lon")
lat <- ncvar_get(nc, "lat")
flat = match(abs(lat - x[2]) < 1/48, 1)
latindex = which(flat %in% 1)
flon = match(abs(lon - x[1]) < 1/48, 1)
lonindex = which(flon %in% 1)
start <- c(lonindex, latindex, 1)
count <- c(1, 1, -1)


# read in the full period of record using aggregated files

#data_aet <- as.numeric(ncvar_get(nc, varid = var,start = start, count))
#data_tmax <- as.numeric(ncvar_get(nc, varid = var,start = start, count))
#data_tmin <- as.numeric(ncvar_get(nc, varid = var,start = start, count))
#data_ws <- as.numeric(ncvar_get(nc, varid = var,start = start, count))
#data_ppt <- as.numeric(ncvar_get(nc, varid = var,start = start, count))

data_lamberts <- data.frame(data_aet, data_tmax, data_tmin, data_ws, data_ppt)

write.csv(data_lamberts,"~/Downloads/data_lamberts.csv", row.names = T)
write.csv(bird_counts,"~/Downloads/bird_counts.csv", row.names = T)
write.csv(sp_counts,"~/Downloads/sp_counts.csv", row.names = T)

```